// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using UrbansenseAPI.Data;

#nullable disable

namespace UrbansenseAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260605174823_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UrbansenseAPI.Domain.Models.Alert", b =>
                {
                    b.Property<decimal>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID_ALERT");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACTIVE");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("CITY");

                    b.Property<decimal>("latitude")
                        .HasColumnType("NUMBER(10,6)")
                        .HasColumnName("LATITUDE");

                    b.Property<decimal>("longitude")
                        .HasColumnType("NUMBER(10,6)")
                        .HasColumnName("LONGITUDE");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(1000)")
                        .HasColumnName("MESSAGE");

                    b.Property<string>("region")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("REGION");

                    b.Property<string>("severity")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("SEVERITY");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("TYPE");

                    b.Property<DateTime>("validFrom")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("VALID_FROM");

                    b.Property<DateTime>("validUntil")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("VALID_UNTIL");

                    b.HasKey("id");

                    b.ToTable("ALERTS", (string)null);
                });

            modelBuilder.Entity("UrbansenseAPI.Domain.Models.TransitLine", b =>
                {
                    b.Property<decimal>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID_LINE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("id"));

                    b.Property<byte>("avgDelayPctOnRain")
                        .HasColumnType("NUMBER(3)")
                        .HasColumnName("AVG_DELAY_PCT");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(10)")
                        .HasColumnName("CODE");

                    b.Property<string>("color")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(10)")
                        .HasColumnName("COLOR");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("NAME");

                    b.Property<decimal>("rainThresholdMm")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("RAIN_THRESHOLD_MM");

                    b.Property<decimal>("rainVulnerabilty")
                        .HasColumnType("NUMBER(4,2)")
                        .HasColumnName("RAIN_VULNERABILITY");

                    b.Property<string>("technician")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("OPERATOR");

                    b.Property<string>("vulnerableSection")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("VULNERABLE_SECTION");

                    b.HasKey("id");

                    b.ToTable("TRANSIT_LINES", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1m,
                            avgDelayPctOnRain = (byte)25,
                            code = "L1",
                            color = "#0155A8",
                            name = "Linha 1 - Azul",
                            rainThresholdMm = 15m,
                            rainVulnerabilty = 0.7m,
                            technician = "Metrô SP",
                            vulnerableSection = "Tucuruvi - Jabaquara"
                        },
                        new
                        {
                            id = 2m,
                            avgDelayPctOnRain = (byte)15,
                            code = "L2",
                            color = "#007E5E",
                            name = "Linha 2 - Verde",
                            rainThresholdMm = 20m,
                            rainVulnerabilty = 0.5m,
                            technician = "Metrô SP",
                            vulnerableSection = "Vila Madalena - Vila Prudente"
                        },
                        new
                        {
                            id = 3m,
                            avgDelayPctOnRain = (byte)30,
                            code = "L3",
                            color = "#EE3124",
                            name = "Linha 3 - Vermelha",
                            rainThresholdMm = 10m,
                            rainVulnerabilty = 0.8m,
                            technician = "Metrô SP",
                            vulnerableSection = "Itaquera - Barra Funda"
                        },
                        new
                        {
                            id = 4m,
                            avgDelayPctOnRain = (byte)10,
                            code = "L4",
                            color = "#FFD400",
                            name = "Linha 4 - Amarela",
                            rainThresholdMm = 25m,
                            rainVulnerabilty = 0.3m,
                            technician = "ViaQuatro",
                            vulnerableSection = "Luz - Butantã"
                        },
                        new
                        {
                            id = 5m,
                            avgDelayPctOnRain = (byte)15,
                            code = "L5",
                            color = "#9B2990",
                            name = "Linha 5 - Lilás",
                            rainThresholdMm = 20m,
                            rainVulnerabilty = 0.5m,
                            technician = "ViaMobilidade",
                            vulnerableSection = "Capão Redondo - Chácara Klabin"
                        },
                        new
                        {
                            id = 6m,
                            avgDelayPctOnRain = (byte)40,
                            code = "L7",
                            color = "#DC241F",
                            name = "Linha 7 - Rubi",
                            rainThresholdMm = 8m,
                            rainVulnerabilty = 0.9m,
                            technician = "CPTM",
                            vulnerableSection = "Luz - Francisco Morato"
                        },
                        new
                        {
                            id = 7m,
                            avgDelayPctOnRain = (byte)35,
                            code = "L8",
                            color = "#97999B",
                            name = "Linha 8 - Diamante",
                            rainThresholdMm = 10m,
                            rainVulnerabilty = 0.85m,
                            technician = "ViaMobilidade",
                            vulnerableSection = "Júlio Prestes - Amador Bueno"
                        },
                        new
                        {
                            id = 8m,
                            avgDelayPctOnRain = (byte)50,
                            code = "L9",
                            color = "#01A651",
                            name = "Linha 9 - Esmeralda",
                            rainThresholdMm = 5m,
                            rainVulnerabilty = 0.95m,
                            technician = "ViaMobilidade",
                            vulnerableSection = "Osasco - Grajaú"
                        },
                        new
                        {
                            id = 9m,
                            avgDelayPctOnRain = (byte)30,
                            code = "L10",
                            color = "#009FC4",
                            name = "Linha 10 - Turquesa",
                            rainThresholdMm = 12m,
                            rainVulnerabilty = 0.8m,
                            technician = "CPTM",
                            vulnerableSection = "Mauá - Brás"
                        },
                        new
                        {
                            id = 10m,
                            avgDelayPctOnRain = (byte)20,
                            code = "L11",
                            color = "#F26522",
                            name = "Linha 11 - Coral",
                            rainThresholdMm = 18m,
                            rainVulnerabilty = 0.6m,
                            technician = "CPTM",
                            vulnerableSection = "Luz - Guaianases"
                        },
                        new
                        {
                            id = 11m,
                            avgDelayPctOnRain = (byte)18,
                            code = "L12",
                            color = "#133E8E",
                            name = "Linha 12 - Safira",
                            rainThresholdMm = 20m,
                            rainVulnerabilty = 0.55m,
                            technician = "CPTM",
                            vulnerableSection = "Brás - Calmon Viana"
                        },
                        new
                        {
                            id = 12m,
                            avgDelayPctOnRain = (byte)10,
                            code = "L13",
                            color = "#00B398",
                            name = "Linha 13 - Jade",
                            rainThresholdMm = 30m,
                            rainVulnerabilty = 0.3m,
                            technician = "CPTM",
                            vulnerableSection = "Engenheiro Goulart - Guarulhos"
                        });
                });

            modelBuilder.Entity("UrbansenseAPI.Domain.Models.Weather", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID_WEATHER");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("CITY");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("CONDITION");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<decimal?>("FeelsLike")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("FEELS_LIKE");

                    b.Property<byte?>("Humidity")
                        .HasColumnType("NUMBER(3)")
                        .HasColumnName("HUMIDITY");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("NUMBER(10,6)")
                        .HasColumnName("LATITUDE");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("NUMBER(10,6)")
                        .HasColumnName("LONGITUDE");

                    b.Property<decimal?>("RainMm")
                        .HasColumnType("NUMBER(6,2)")
                        .HasColumnName("RAIN_MM");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("RECORDED_AT");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("NUMBER(5,2)")
                        .HasColumnName("TEMPERATURE");

                    b.Property<byte?>("UvIndex")
                        .HasColumnType("NUMBER(3)")
                        .HasColumnName("UV_INDEX");

                    b.Property<decimal?>("WindSpeed")
                        .HasColumnType("NUMBER(6,2)")
                        .HasColumnName("WIND_SPEED");

                    b.HasKey("Id");

                    b.ToTable("WEATHER_RECORDS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
